import { useState, useCallback, useEffect } from "react";
import { X } from "lucide-react";
import { saveSpecDocument } from "../../lib/tauri-commands";
import { showToast } from "../../stores/toastStore";
import { useSpecWriterStore } from "../../stores/specWriterStore";
import { useGuideStore } from "../../stores/guideStore";
import { useUiStore } from "../../stores/uiStore";
import { parseSessionPlan } from "../../lib/parse-session-plan";

interface Props {
  projectPath: string;
  specContent: string;
  aiModel: string;
  mode: string;
  documentType: 'spec' | 'audit';
  lastSavedFile?: string | null;
  onClose: () => void;
  onSaved: (filename: string) => void;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
}

export default function SaveSpecDialog({ projectPath, specContent, aiModel, mode, documentType, lastSavedFile, onClose, onSaved }: Props) {
  const [filename, setFilename] = useState("");
  const [overwrite, setOverwrite] = useState(false);
  const [saving, setSaving] = useState(false);
  const [fileExists, setFileExists] = useState(false);
  const savedSpecs = useSpecWriterStore((s) => s.savedSpecs.get(projectPath) ?? []);

  const isAudit = documentType === 'audit';
  const dialogTitle = isAudit ? "Save Verification Audit" : "Save Specification";

  // Pre-fill filename from spec title or derive audit filename from current spec
  useEffect(() => {
    if (isAudit) {
      // Prefer the just-saved spec filename for correct pairing
      if (lastSavedFile) {
        setFilename(lastSavedFile.replace(/\.md$/, '.audit.md'));
      } else {
        // Fallback: derive from most recently saved spec on disk
        const specs = savedSpecs.filter((s) => !s.filename.endsWith('.audit.md'));
        const latestSpec = specs.length > 0 ? specs[specs.length - 1] : null;
        if (latestSpec) {
          setFilename(latestSpec.filename.replace(/\.md$/, '.audit.md'));
        } else {
          // Last resort: extract title from audit content
          const titleMatch = specContent.match(/^#\s+(.+?)(?:\s*[—-]\s*.+)?$/m);
          setFilename(titleMatch ? slugify(titleMatch[1]) + '.audit.md' : `audit-${Date.now()}.md`);
        }
      }
    } else {
      const titleMatch = specContent.match(/^#\s+(.+?)(?:\s*[—-]\s*.+)?$/m);
      if (titleMatch) {
        setFilename(slugify(titleMatch[1]) + ".md");
      } else {
        setFilename(`spec-${Date.now()}.md`);
      }
    }
  }, [specContent, isAudit, savedSpecs, lastSavedFile]);

  // Check if file exists
  useEffect(() => {
    const exists = savedSpecs.some((s) => s.filename === filename);
    setFileExists(exists);
    if (!exists) setOverwrite(false);
  }, [filename, savedSpecs]);

  const handleSave = useCallback(async () => {
    if (!filename.trim()) return;
    if (fileExists && !overwrite) return;

    setSaving(true);
    try {
      // Prepend metadata header
      const now = new Date().toISOString().split('T')[0];
      let header: string;
      if (isAudit) {
        const specFilename = filename.replace('.audit.md', '.md');
        header = `<!-- \n  Generated by CodeMantis SpecWriter\n  Date: ${now}\n  AI Model: ${aiModel}\n  Type: Verification Audit\n  Spec: ${specFilename}\n  Project: ${projectPath}\n-->\n\n`;
      } else {
        header = `<!-- \n  Generated by CodeMantis SpecWriter\n  Date: ${now}\n  AI Model: ${aiModel}\n  Mode: ${mode}\n  Project: ${projectPath}\n-->\n\n`;
      }
      const fullContent = header + specContent;

      await saveSpecDocument(projectPath, filename, fullContent, overwrite || !fileExists);
      showToast(`${isAudit ? 'Audit' : 'Spec'} saved to docs/specs/${filename}`, "success");
      onSaved(filename);

      // After spec save, try to create an implementation guide from Session Plan
      if (!isAudit) {
        try {
          const parsed = parseSessionPlan(specContent);
          if (parsed) {
            const created = await useGuideStore.getState().createGuide(
              projectPath, filename, null, parsed,
            );
            if (created) {
              showToast(
                `Implementation Guide created \u2014 ${parsed.sessions.length} sessions to complete`,
                "info",
              );
              useUiStore.getState().setRightTab("guide");
            }
          }
        } catch (guideErr) {
          // Non-fatal: guide creation failure shouldn't block spec save
          console.warn("[SaveSpecDialog] Failed to create implementation guide:", guideErr);
        }
      }
    } catch (e) {
      showToast(`Failed to save: ${e}`, "error");
    } finally {
      setSaving(false);
    }
  }, [filename, fileExists, overwrite, specContent, projectPath, aiModel, mode, isAudit, onSaved]);

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center" style={{ background: "rgba(0,0,0,0.5)" }}>
      <div
        className="w-[400px] rounded-lg shadow-2xl overflow-hidden"
        style={{ background: "var(--bg-primary)", border: "1px solid var(--border)" }}
      >
        <div
          className="flex items-center justify-between px-4 py-3 border-b"
          style={{ borderColor: "var(--border)", background: "var(--bg-secondary)" }}
        >
          <span className="text-sm font-medium" style={{ color: "var(--text-primary)" }}>
            {dialogTitle}
          </span>
          <button
            onClick={onClose}
            className="p-1 rounded hover:bg-bg-elevated transition-colors"
            style={{ color: "var(--text-ghost)" }}
          >
            <X size={14} />
          </button>
        </div>

        <div className="px-4 py-3 space-y-3">
          <div>
            <label className="block text-xs mb-1" style={{ color: "var(--text-secondary)" }}>
              Filename
            </label>
            <input
              type="text"
              value={filename}
              onChange={(e) => setFilename(e.target.value)}
              className="w-full px-3 py-2 rounded-md text-sm outline-none"
              style={{
                background: "var(--bg-elevated)",
                color: "var(--text-primary)",
                border: "1px solid var(--border)",
              }}
              placeholder={isAudit ? "my-feature.audit.md" : "my-spec.md"}
            />
            <div className="text-[10px] mt-1" style={{ color: "var(--text-ghost)" }}>
              Saves to: docs/specs/{filename || "..."}
            </div>
          </div>

          {fileExists && (
            <div
              className="flex items-center gap-2 px-3 py-2 rounded-md text-xs"
              style={{ background: "rgba(234,179,8,0.1)", color: "#ca8a04" }}
            >
              <span>File already exists.</span>
              <button
                onClick={() => setOverwrite(true)}
                className="underline font-medium"
              >
                Overwrite
              </button>
              <span>or</span>
              <button
                onClick={() => {
                  const ext = isAudit ? '.audit.md' : '.md';
                  const base = filename.replace(ext, '');
                  setFilename(`${base}-v2${ext}`);
                }}
                className="underline font-medium"
              >
                Save as {filename.replace(isAudit ? '.audit.md' : '.md', '')}-v2{isAudit ? '.audit.md' : '.md'}
              </button>
            </div>
          )}

          <div className="flex justify-end gap-2 pt-1">
            <button
              onClick={onClose}
              className="px-4 py-2 rounded-md text-xs transition-colors hover:brightness-95"
              style={{
                background: "var(--bg-elevated)",
                color: "var(--text-secondary)",
                border: "1px solid var(--border)",
              }}
            >
              Cancel
            </button>
            <button
              onClick={handleSave}
              disabled={saving || !filename.trim() || (fileExists && !overwrite)}
              className="px-4 py-2 rounded-md text-xs font-medium transition-colors hover:opacity-90 disabled:opacity-40"
              style={{ background: "var(--accent)", color: "white" }}
            >
              {saving ? "Saving..." : "Save"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
