import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { useSpecWriterStore } from "../../stores/specWriterStore";

const mockSaveSpecDocument = vi.fn().mockResolvedValue("/tmp/docs/specs/test.md");
vi.mock("../../lib/tauri-commands", () => ({
  saveSpecDocument: (...args: unknown[]) => mockSaveSpecDocument(...args),
}));

vi.mock("../../stores/toastStore", () => ({
  showToast: vi.fn(),
}));

import SaveSpecDialog from "./SaveSpecDialog";
import { normalizeAuditCompanion } from "../../lib/audit-companion";

const PROJECT = "/tmp/test";

beforeEach(() => {
  useSpecWriterStore.setState({
    conversations: new Map(),
    currentSpecContent: new Map(),
    currentAuditContent: new Map(),
    savedSpecs: new Map([[PROJECT, []]]),
  });
  vi.clearAllMocks();
});

describe("SaveSpecDialog", () => {
  const baseProps = {
    projectPath: PROJECT,
    specContent: "# My Feature — Requirements Specification\n\nSome content",
    aiModel: "gemini-2.5-flash",
    mode: "Feature (existing project)",
    onClose: vi.fn(),
    onSaved: vi.fn(),
  };

  describe("spec mode", () => {
    it("renders with spec title", () => {
      render(<SaveSpecDialog {...baseProps} documentType="spec" />);
      expect(screen.getByText("Save Specification")).toBeTruthy();
    });

    it("auto-generates filename from spec title", () => {
      render(<SaveSpecDialog {...baseProps} documentType="spec" />);
      // Title regex captures "My Feature" (before the em dash), slugified to "my-feature"
      const input = screen.getByDisplayValue("my-feature.md");
      expect(input).toBeTruthy();
    });

    it("saves with spec metadata header", async () => {
      render(<SaveSpecDialog {...baseProps} documentType="spec" />);
      fireEvent.click(screen.getByText("Save"));
      await waitFor(() => {
        expect(mockSaveSpecDocument).toHaveBeenCalled();
      });
      const savedContent = mockSaveSpecDocument.mock.calls[0][2] as string;
      expect(savedContent).toContain("Generated by CodeMantis SpecWriter");
      expect(savedContent).toContain("Mode:");
      expect(savedContent).not.toContain("Type: Verification Audit");
    });
  });

  describe("audit mode", () => {
    it("renders with audit title", () => {
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      expect(screen.getByText("Save Verification Audit")).toBeTruthy();
    });

    it("derives audit filename from latest saved spec", () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
        ]]]),
      });
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      const input = screen.getByDisplayValue("my-feature.audit.md");
      expect(input).toBeTruthy();
    });

    it("falls back to title-based filename when no saved spec exists", () => {
      render(
        <SaveSpecDialog
          {...baseProps}
          specContent="# Dashboard — Verification Audit\n\nContent"
          documentType="audit"
        />
      );
      // Title regex captures "Dashboard" (before the em dash), slugified to "dashboard"
      const input = screen.getByDisplayValue("dashboard.audit.md");
      expect(input).toBeTruthy();
    });

    it("saves with audit metadata header", async () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
        ]]]),
      });
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      fireEvent.click(screen.getByText("Save"));
      await waitFor(() => {
        expect(mockSaveSpecDocument).toHaveBeenCalled();
      });
      const savedContent = mockSaveSpecDocument.mock.calls[0][2] as string;
      expect(savedContent).toContain("Type: Verification Audit");
      expect(savedContent).toContain("Spec: my-feature.md");
    });

    it("ignores audit files when deriving filename from saved specs", () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
          { filename: "my-feature.audit.md", title: "My Feature Audit", modified_at: "", size_bytes: 200, path: "" },
        ]]]),
      });
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      // Should derive from "my-feature.md", not from "my-feature.audit.md"
      const input = screen.getByDisplayValue("my-feature.audit.md");
      expect(input).toBeTruthy();
    });
  });

  it("calls onClose when Cancel is clicked", () => {
    render(<SaveSpecDialog {...baseProps} documentType="spec" />);
    fireEvent.click(screen.getByText("Cancel"));
    expect(baseProps.onClose).toHaveBeenCalled();
  });

  it("calls onSaved after successful save", async () => {
    render(<SaveSpecDialog {...baseProps} documentType="spec" />);
    fireEvent.click(screen.getByText("Save"));
    await waitFor(() => {
      expect(baseProps.onSaved).toHaveBeenCalled();
    });
  });

  describe("normalizeAuditCompanion", () => {
    it("substitutes the <SPEC_FILENAME> token", () => {
      const input = `# Foo Bar — Verification Audit\n\n**Companion to:** \`docs/specs/<SPEC_FILENAME>\`\n`;
      const out = normalizeAuditCompanion(input, "foo-bar.md");
      expect(out).toContain("docs/specs/foo-bar.md");
      expect(out).not.toContain("<SPEC_FILENAME>");
    });

    it("rewrites a hallucinated Companion to: path to the saved filename", () => {
      const input = `# Site Migration — Verification Audit\n\n**Companion to:** \`docs/specs/site-nextjs.md\`\n`;
      const out = normalizeAuditCompanion(input, "gradum-public-site.md");
      expect(out).toContain("docs/specs/gradum-public-site.md");
      expect(out).not.toContain("site-nextjs.md");
    });

    it("leaves an already-correct Companion to: line untouched", () => {
      const input = `**Companion to:** \`docs/specs/foo-bar.md\``;
      expect(normalizeAuditCompanion(input, "foo-bar.md")).toBe(input);
    });
  });

  describe("filename soft warning", () => {
    it("renders a generic-name warning for one-token slugs", () => {
      render(
        <SaveSpecDialog
          {...baseProps}
          specContent="# Gradum — Requirements Specification\n"
          documentType="spec"
        />,
      );
      expect(screen.getByDisplayValue("gradum.md")).toBeTruthy();
      expect(screen.getByText(/Filename looks generic/)).toBeTruthy();
    });

    it("does not render the warning for descriptive multi-word slugs", () => {
      render(
        <SaveSpecDialog
          {...baseProps}
          specContent="# Gradum Public Site Migration — Requirements Specification\n"
          documentType="spec"
        />,
      );
      expect(screen.getByDisplayValue("gradum-public-site-migration.md")).toBeTruthy();
      expect(screen.queryByText(/Filename looks generic/)).toBeNull();
    });
  });

  describe("audit save substitution wiring", () => {
    it("normalizes <SPEC_FILENAME> in the saved audit body", async () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
        ]]]),
      });
      render(
        <SaveSpecDialog
          {...baseProps}
          specContent={
            "# My Feature — Verification Audit\n\n" +
            "**Companion to:** `docs/specs/<SPEC_FILENAME>`\n\nBody."
          }
          documentType="audit"
        />,
      );
      fireEvent.click(screen.getByText("Save"));
      await waitFor(() => {
        expect(mockSaveSpecDocument).toHaveBeenCalled();
      });
      const savedContent = mockSaveSpecDocument.mock.calls[0][2] as string;
      expect(savedContent).toContain("docs/specs/my-feature.md");
      expect(savedContent).not.toContain("<SPEC_FILENAME>");
    });

    it("rewrites a hallucinated audit Companion path on save", async () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "gradum-public-site.md", title: "Gradum Public Site", modified_at: "", size_bytes: 100, path: "" },
        ]]]),
      });
      render(
        <SaveSpecDialog
          {...baseProps}
          specContent={
            "# Gradum Public Site — Verification Audit\n\n" +
            "**Companion to:** `docs/specs/gradum-public-nextjs.md`\n\nBody."
          }
          documentType="audit"
        />,
      );
      fireEvent.click(screen.getByText("Save"));
      await waitFor(() => {
        expect(mockSaveSpecDocument).toHaveBeenCalled();
      });
      const savedContent = mockSaveSpecDocument.mock.calls[0][2] as string;
      expect(savedContent).toContain("docs/specs/gradum-public-site.md");
      expect(savedContent).not.toContain("gradum-public-nextjs.md");
    });
  });
});
