import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import { useSpecWriterStore } from "../../stores/specWriterStore";

const mockSaveSpecDocument = vi.fn().mockResolvedValue("/tmp/docs/specs/test.md");
vi.mock("../../lib/tauri-commands", () => ({
  saveSpecDocument: (...args: unknown[]) => mockSaveSpecDocument(...args),
}));

vi.mock("../../stores/toastStore", () => ({
  showToast: vi.fn(),
}));

import SaveSpecDialog from "./SaveSpecDialog";

const PROJECT = "/tmp/test";

beforeEach(() => {
  useSpecWriterStore.setState({
    conversations: new Map(),
    currentSpecContent: new Map(),
    currentAuditContent: new Map(),
    savedSpecs: new Map([[PROJECT, []]]),
  });
  vi.clearAllMocks();
});

describe("SaveSpecDialog", () => {
  const baseProps = {
    projectPath: PROJECT,
    specContent: "# My Feature — Requirements Specification\n\nSome content",
    aiModel: "gemini-2.5-flash",
    mode: "Feature (existing project)",
    onClose: vi.fn(),
    onSaved: vi.fn(),
  };

  describe("spec mode", () => {
    it("renders with spec title", () => {
      render(<SaveSpecDialog {...baseProps} documentType="spec" />);
      expect(screen.getByText("Save Specification")).toBeTruthy();
    });

    it("auto-generates filename from spec title", () => {
      render(<SaveSpecDialog {...baseProps} documentType="spec" />);
      // Title regex captures "My Feature" (before the em dash), slugified to "my-feature"
      const input = screen.getByDisplayValue("my-feature.md");
      expect(input).toBeTruthy();
    });

    it("saves with spec metadata header", async () => {
      render(<SaveSpecDialog {...baseProps} documentType="spec" />);
      fireEvent.click(screen.getByText("Save"));
      await waitFor(() => {
        expect(mockSaveSpecDocument).toHaveBeenCalled();
      });
      const savedContent = mockSaveSpecDocument.mock.calls[0][2] as string;
      expect(savedContent).toContain("Generated by CodeMantis SpecWriter");
      expect(savedContent).toContain("Mode:");
      expect(savedContent).not.toContain("Type: Verification Audit");
    });
  });

  describe("audit mode", () => {
    it("renders with audit title", () => {
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      expect(screen.getByText("Save Verification Audit")).toBeTruthy();
    });

    it("derives audit filename from latest saved spec", () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
        ]]]),
      });
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      const input = screen.getByDisplayValue("my-feature.audit.md");
      expect(input).toBeTruthy();
    });

    it("falls back to title-based filename when no saved spec exists", () => {
      render(
        <SaveSpecDialog
          {...baseProps}
          specContent="# Dashboard — Verification Audit\n\nContent"
          documentType="audit"
        />
      );
      // Title regex captures "Dashboard" (before the em dash), slugified to "dashboard"
      const input = screen.getByDisplayValue("dashboard.audit.md");
      expect(input).toBeTruthy();
    });

    it("saves with audit metadata header", async () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
        ]]]),
      });
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      fireEvent.click(screen.getByText("Save"));
      await waitFor(() => {
        expect(mockSaveSpecDocument).toHaveBeenCalled();
      });
      const savedContent = mockSaveSpecDocument.mock.calls[0][2] as string;
      expect(savedContent).toContain("Type: Verification Audit");
      expect(savedContent).toContain("Spec: my-feature.md");
    });

    it("ignores audit files when deriving filename from saved specs", () => {
      useSpecWriterStore.setState({
        savedSpecs: new Map([[PROJECT, [
          { filename: "my-feature.md", title: "My Feature", modified_at: "", size_bytes: 100, path: "" },
          { filename: "my-feature.audit.md", title: "My Feature Audit", modified_at: "", size_bytes: 200, path: "" },
        ]]]),
      });
      render(<SaveSpecDialog {...baseProps} documentType="audit" />);
      // Should derive from "my-feature.md", not from "my-feature.audit.md"
      const input = screen.getByDisplayValue("my-feature.audit.md");
      expect(input).toBeTruthy();
    });
  });

  it("calls onClose when Cancel is clicked", () => {
    render(<SaveSpecDialog {...baseProps} documentType="spec" />);
    fireEvent.click(screen.getByText("Cancel"));
    expect(baseProps.onClose).toHaveBeenCalled();
  });

  it("calls onSaved after successful save", async () => {
    render(<SaveSpecDialog {...baseProps} documentType="spec" />);
    fireEvent.click(screen.getByText("Save"));
    await waitFor(() => {
      expect(baseProps.onSaved).toHaveBeenCalled();
    });
  });
});
