// Yellow warning banner shown above any catalog entry whose `trust_tier`
// is `ai_generated` (Phase 5). Phase 3 ships the component so Mission
// Control's render path is complete; the banner only appears when AI-fallback
// catalog generation kicks in (Phase 5).

import { AlertTriangle } from "lucide-react";

interface AiGeneratedBannerProps {
  /** Whether two other AIs cross-checked and agreed on the structure. */
  crossVerified?: boolean;
}

export default function AiGeneratedBanner({
  crossVerified = false,
}: AiGeneratedBannerProps) {
  return (
    <div
      className="rounded-md border p-3 flex items-start gap-2.5"
      style={{
        borderColor: "rgb(234, 179, 8)",
        background: "color-mix(in srgb, rgb(234, 179, 8) 10%, transparent)",
      }}
    >
      <AlertTriangle
        size={16}
        className="shrink-0 mt-0.5"
        style={{ color: "rgb(234, 179, 8)" }}
      />
      <div className="text-detail leading-snug" style={{ color: "rgb(234, 179, 8)" }}>
        <strong>AI-generated guidance.</strong>{" "}
        {crossVerified
          ? "Two other AI providers confirmed the structure of these instructions, but no human has reviewed them. Double-check before pasting any sensitive value."
          : "These instructions were generated by AI and haven't been verified by the CodeMantis team or any second AI. Double-check before following — especially before pasting any secret."}
      </div>
    </div>
  );
}
